site_name: Research Software Summer School
repo_url: https://github.com/CentreForDigitalFumanities/research-software-summer-school


# styling
theme:
  name: material
  palette:
    primary: custom
    accent: custom
  font:
    text: Open Sans
  logo: assets/cdh_avatar.jpg
extra_css:
  - stylesheets/extra.css
