# metadata
site_name: Research Software Summer School
repo_url: https://github.com/CentreForDigitalFumanities/research-software-summer-school

# markdown options
plugins:
  - awesome-nav
  - privacy:
      links_attr_map:
        target: _blank
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.blocks.admonition
  - pymdownx.blocks.caption
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true

# styling
theme:
  name: material
  palette:
    primary: custom
    accent: custom
  font:
    text: Open Sans
  features:
    - content.code.copy
  logo: assets/cdh_avatar.jpg
extra_css:
  - stylesheets/extra.css